### ISSUE TITLE
LENGOW_URL and LENGOW_API_URL constants

### ISSUE THREAD

**Issue by VincentMarmiesse** [lengow/plugin-magento2#3]
Hello,

I don't understand why you stored the Lengow url and Lengow API url into constants, it causes a lot of issues:

- We must modify the Lengow module code and our modification will be erased at every update
- We must have a different code version between production and staging
- If we install the module via Composer, we can't modify the module code
- `dev` and `master` branches have these values configured to `lengow.io` so we can't select a production branch

Why didn't you put these values in config?

Is there any plan to change this behavior?

Thank you.

**Comment by thedotwriter** [comment]
Please, please, please, add a setting in the backend that will allows us to switch between preproduction & production.

The only viable way to use your module right now is for us to create a custom release that will allow us to do that...

**Comment by mdlonline** [comment]
By changing the URL to https://api.lengow.net on the master branch the order sync stopped working on our production site. I have no clue why you have changed this on the master branch.

**Comment by Detzler** [comment]
+1

I couldn't trust my eyes seeing this while integrating the module into a project. Need the PR as soon as possible in the upcoming 1.4.3 version please. @benjaminlgw @Clovis-lgw

**Comment by thedotwriter** [comment]
New fun fact about this that can put you into a world of troubles:

On repo.magento.com :
The `1.4.4` release has a Connector.php file that points by default to lengow.io

On github :
The `1.4.4` release has a Connector.php file that points by default to lengow.dev

Same release tag, different code. **Scary**.

This made our project use the production env while we were confident we were using the sandbox env.

**Comment by thedotwriter** [comment]
This can be closed. Environment is now configurable from the backend since 1.5.0.

Can't expect the maintainers to close resolved issues ¯ \ _ (ツ) _ / ¯.  

This is referenced in the CHANGELOG file as a feature from the "1.4.7" release but the release does not exist in the repository. Gotta love the team behind this module.

**Comment by Detzler** [comment]
Thanks for the info @thedotwriter
